In [1]:
import pandas as pd


In [44]:
df = pd.read_csv('/home/robotlab/projects/bimanual-infra/data/env_state_action_df_192.168.86.230.csv')

In [45]:
df.keys()


Index(['created_timestamp', 'pose_aa', 'joint_angles', 'gripper_state',
       'force_info', 'action_des_pose_aa', 'controller_ts', 'last_sent_ts'],
      dtype='object')

In [132]:
df['created_timestamp'][1],df['created_timestamp'][0],

(1683828065.9130034, 1683828063.1581635)

In [92]:
import numpy as np
obs = np.array([k.strip("[").strip("]").split() for k in df['pose_aa'].to_numpy()], dtype=float)
obs_prime = np.array(np.concatenate([obs[1:], np.expand_dims(obs[-1], axis=0)]), dtype=float)
actions = np.array([k.strip("[").strip("]").split() for k in df['action_des_pose_aa'][1:].to_numpy()], dtype=float)

# actions = np.concat

In [128]:
obs[:-1] - obs[1:]


array([[-8.400e-02,  1.318e+00,  3.945e+00, -6.270e+00,  3.000e-03,
         1.200e-02],
       [-2.700e-02,  3.300e-02,  3.270e-01,  0.000e+00, -1.000e-03,
        -1.000e-03],
       [ 0.000e+00, -4.500e-02,  3.800e-02,  0.000e+00,  0.000e+00,
         0.000e+00],
       ...,
       [-4.000e-02,  8.200e-02,  8.600e-02,  1.000e-03,  0.000e+00,
         0.000e+00],
       [-4.300e-02,  7.500e-02,  5.500e-02,  0.000e+00, -1.000e-03,
         0.000e+00],
       [-3.700e-02,  1.300e-02,  3.900e-02, -1.000e-03,  0.000e+00,
        -1.000e-03]])

In [115]:
actions[12], obs_prime[12]

(array([ 2.06266e+02, -5.15000e-01,  4.71291e+02, -3.13700e+00,
        -3.00000e-03, -1.00000e-02]),
 array([ 2.05934e+02, -1.24800e+00,  4.69291e+02,  3.12900e+00,
        -1.00000e-03, -3.00000e-03]))

In [116]:
from scipy.spatial.transform import Rotation as R

In [123]:
def print_quat(x):
    q = R.from_rotvec(x).as_quat()
    print(q)
    
    
print_quat(actions[12][3:])
print_quat(obs_prime[12][3:])

[-9.99991845e-01 -9.56319903e-04 -3.18773301e-03  2.28763818e-03]
[ 9.99979673e-01 -3.19584427e-04 -9.58753281e-04  6.29548623e-03]


In [124]:
np.array([actions[i] - obs_prime[i] for i in range(len(actions))])

array([[ 1.330e-01,  1.290e+00,  2.000e+00, -6.271e+00,  2.000e-03,
         6.000e-03],
       [ 1.060e-01,  1.323e+00,  2.000e+00, -6.271e+00,  1.000e-03,
         5.000e-03],
       [ 1.060e-01,  1.278e+00,  2.000e+00, -6.271e+00,  1.000e-03,
         5.000e-03],
       ...,
       [ 2.000e+00, -2.000e+00,  2.000e+00,  8.000e-03,  2.900e-02,
         3.000e-03],
       [ 2.000e+00, -2.000e+00,  2.000e+00,  1.000e-02,  3.000e-02,
         0.000e+00],
       [ 2.000e+00, -2.000e+00,  2.000e+00,  1.400e-02,  3.400e-02,
        -4.000e-03]])

In [80]:
obs[0]

array([ 2.05783e+02,  2.80000e-02,  4.73922e+02, -3.14100e+00,
        1.00000e-03,  6.00000e-03])

In [62]:
len(obs), len(obs_prime)

(311, 310)

In [49]:
df['pose_aa']

0      [205.783   0.028 473.922  -3.141   0.001   0.006]
1      [205.867  -1.29  469.977   3.129  -0.002  -0.006]
2      [205.894  -1.323 469.65    3.129  -0.001  -0.005]
3      [205.894  -1.278 469.612   3.129  -0.001  -0.005]
4      [205.893  -1.268 469.627   3.129  -0.001  -0.005]
                             ...                        
306    [219.881 -15.15  412.994  -3.117   0.225  -0.036]
307    [219.924 -15.179 412.896  -3.118   0.226  -0.035]
308    [219.964 -15.261 412.81   -3.119   0.226  -0.035]
309    [220.007 -15.336 412.755  -3.119   0.227  -0.035]
310    [220.044 -15.349 412.716  -3.118   0.227  -0.034]
Name: pose_aa, Length: 311, dtype: object

In [26]:
numpy_array = np.array([np.fromstring(elem, dtype=float, sep=' ') for elem in x])


/tmp/ipykernel_1187408/749999945.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  numpy_array = np.array([np.fromstring(elem, dtype=float, sep=' ') for elem in x])


In [27]:
[np.fromstring(elem, dtype=float, sep=' ') for elem in x]

/tmp/ipykernel_1187408/1824817947.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  [np.fromstring(elem, dtype=float, sep=' ') for elem in x]


[array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 

In [35]:
k = x[0].strip("[").strip("]").split()

In [37]:
np.array(k, dtype=float)

array([ 2.05783e+02,  2.80000e-02,  4.73922e+02, -3.14100e+00,
        1.00000e-03,  6.00000e-03])